{{ config(
    materialized="incremental",
    schema="DWh",
    Unique_id='opportunityid'
    ) 
}}

with final as (
SELECT 
"id" as "d_opportunity_key",
"id" as "opportunityid",
"isdeleted"	as "isdeleted",
"accountid"	as "accountid",
"name"	as "name",
"description"	as "description",
"stagename"	as "stagename",
"closedate"	as "closedate",
"type"	as "type",
"nextstep"	as "nextstep",
"leadsource"	as "leadsource",
"isclosed"	as "isclosed",
"iswon"	as "iswon",
"forecastcategory"	as "forecastcategory",
"forecastcategoryname"	as "forecastcategoryname",
"campaignid"	as "campaignid",
"hasopportunitylineitem"	as "hasopportunitylineitem",
"pricebook2id"	as "pricebook2id",
"ownerid"	as "ownerid",
"createddate"	as "createddate",
"createdbyid"	as "createdbyid",
"lastmodifieddate"	as "lastmodifieddate",
"lastmodifiedbyid"	as "lastmodifiedbyid",
"lastactivitydate"	as "lastactivitydate",
"fiscalquarter"	as "fiscalquarter",
"fiscalyear"	as "fiscalyear",
"fiscal"	as "fiscal",
"lastvieweddate"	as "lastvieweddate",
"lastreferenceddate"	as "lastreferenceddate",
"hasopenactivity"	as "hasopenactivity",
"hasoverduetask"	as "hasoverduetask",
"ageindays"	as "ageindays",
"connectionreceivedid"	as "connectionreceivedid",
"connectionsentid"	as "connectionsentid",
"contactid"	as "contactid",
"contractid"	as "contractid",
"iqscore"	as "iqscore",
"isexcludedfromterritory2filter"	as "isexcludedfromterritory2filter",
"issplit"	as "issplit",
"lastactivityindays"	as "lastactivityindays",
"lastamountchangedhistoryid"	as "lastamountchangedhistoryid",
"lastclosedatechangedhistoryid"	as "lastclosedatechangedhistoryid",
"laststagechangedate"	as "laststagechangedate",
"laststagechangeindays"	as "laststagechangeindays",
"partneraccountid"	as "partneraccountid",
"pricebookid"	as "pricebookid",
"recordtypeid"	as "recordtypeid",
"syncedquoteid"	as "syncedquoteid",
"territory2id"	as "territory2id",
"executiondate"	as "executiondate",
null as "d_account_key"
FROM {{ ref('recp_opportunity') }} 
)
select * from final
